{% set name = "glom" %}
{% set version = "20.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1cd096c2dce31e3b08c2c5bd4862ef9c30f1f1946aded8bc5062a14284cde07

build:
  number: 0
  entry_points:
    - glom = glom.cli:console_main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - attrs
    - boltons
    - face
    - python

test:
  imports:
    - glom
    - glom.test
  commands:
    - glom --help

about:
  home: https://github.com/mahmoud/glom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A declarative object transformer and formatter, for conglomerating nested data.

extra:
  recipe-maintainers:
    - CJ-Wright
