{% set name = "glom" %}
{% set version = "23.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7442309e013feb6feab206197abf8aec32835ec709d8a92a8514322f64c0eff

build:
  number: 0
  entry_points:
    - glom = glom.cli:console_main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs <=19.1.0
    - boltons >=19.3.0
    - face >=20.1.0
    - python >=3.6

test:
  source_files:
    - glom/test
  imports:
    - glom
  commands:
    - pip check
    - glom --help
    - pytest -vvv glom/test
  requires:
    - pip
    - pytest ==4.1.1
    - pyyaml ==5.4.1

about:
  home: https://github.com/mahmoud/glom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A declarative object transformer and formatter, for conglomerating nested data.

extra:
  recipe-maintainers:
    - CJ-Wright
    - thewchan
