travis:
  secure:
    BINSTAR_TOKEN: afSKXkrxSvzXrM6cGumMmbfGAT98zenRjuc/UlQpc38+0gRW3omygzLe1U/+GSaVHIpKtHETxTwrGIDRfXUYm6KrK00k2ulnpQgzoTqH6HjKLsjtQBd6H7+601MPb3OfUAWREbihocvyjlVaXrTXGTtO0EfEb/M6O2eiRxgpXy2PBM7ZvPdi/gBScBz+xBel3npZG2cnu4M/71uXPSsQNA371CAMOwi0Xj66hPbQBTBoxXKf2doceAw2JVmSLhSU3ZlYrv6HxphiRN/zaYwLM7fjRQwyVKndl8ucfw68qdZA+wzaLqqJrhh8OHCkYN4K24CFmsjJuJZuSjnyUFTogATv8HpBdHDLG6fQ+/jH5gLhaHBt1GYpIwiFwF83FZdszwIpdiPdTTkPu4l199SCcD7e3keg5nsAwRlMFz3s3pI9bZzU1Xjja5seP9ayfbbAfNOodlqVyDEK4TIHyWdssxC4Dh/MfBuefEqTZvfebcl8VoNyYXwXl1gW2xsHenVtfvlYVxRt6Rvj3AZLmzvUXCJt01HP4XR0ElInaOCnHCQphmyS6Xhs0mJFgX+G6BN6GALAJtM9fcWJcwKwbzcTr6/2NYfpCl+S8J5aoU7ygPhPtMSvmnvKElHEGckFngFjC5hfVkmkCB/yvhM2HPxf1xNcH7ldUseuIAHkf2UxKmo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
